### ISSUE TITLE
Pool/Remove Liquidity/Remove/Sign doesn't work with Ledger+MetaMask or AlphaWallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [Uniswap/uniswap-frontend#795]
**Bug Description**
Pool/Remove Liquidity/Remove/Sign doesn't work with Ledger+MetaMask or AlphaWallet (iOS and Andriod)

**Steps to Reproduce**
1. Go to Pool/Remove Liquidity/Remove/Sign
2. Click on Sign
Ledger+MetaMask: MetaMask popup signing page, but won't ask for signing on Ledger
AlphaWallet: nothing happens

BTW, what is this Signing for?

**Comment by NoahZinsmeister** [comment]
the signature is passed to [`permit`](https://uniswap.org/docs/v2/technical-considerations/using-permit/), which approves the router for the LP tokens. we're using the [`signTypedData_v4`](https://metamask.github.io/metamask-docs/guide/signing-data.html#sign-typed-data-v4) method, it's likely that ledger and alphawallet don't support thi.

if necessary, an approval can be manually completed on the pair contract in question. we could also fallback to manually prompting an approval transaction if the signature fails.

**Comment by trixiebits** [comment]
Captured from the Firefox console, left out the trace:

`code: -32603
​data: Object { originalError: {} }
​message: "MetaMask Message Signature: Error: Not supported on this device"`

Would it be possible to have a more detailed workaround for this - I'd imagine there are quite a number of people with Ledgers wanting to adjust liquidity. Thank you

**Comment by trixiebits** [comment]
@NoahZinsmeister sorry to bother but a quick fix or workaround is much appreciated, otherwise people with me with Ledgers will have their money stuck onchain.

**Comment by lightuponlight** [comment]
I have the same problem.

**Comment by lightuponlight** [comment]
Also, has Ledger been contacted about supporting signTypedData_v4?

**Comment by NoahZinsmeister** [comment]
should have a fix for this within the next ~12 hours

**Comment by lightuponlight** [comment]
great, thanks Noah!

**Comment by NoahZinsmeister** [comment]
this should be fixed! if anyone continues to have problems, please comment and i'll be happy to reopen the issue

**Comment by lightuponlight** [comment]
Worked great!

Can you guys also reach out to Ledger so they can update their code for the off-chain signature too?

Thanks!

**Comment by MoonWalkerAZ** [comment]
I still have an error with metamask on ledger:
`{code: -32603, message: "MetaMask Message Signature: Error: Not supported on this device", data: {…}, stack: "Error: MetaMask Message Signature: Error: Not supp…eogaeaoehlefnkodbefgpgknn/background.js:1:179587)"}`

**Comment by cazala** [comment]
Having this same problem using the uniswap interface to depositing LP tokens to get UNI rewards. Nothing shows up on Ledger, and the error in the console shows `MetaMask Message Signature: Error: Not supported on this device`

**Comment by moodysalem** [comment]
Please give this 15 minutes and refresh, then try again.

**Comment by MoonWalkerAZ** [comment]
I have tried multiple times a day and still same issue.

**Comment by MoonWalkerAZ** [comment]
It worked now.

**Comment by TheOnionco** [comment]
Hi There, im having the same issues as the guys above can any body help, i cant sign on my ledegr to approve a Uniswap tracaction

**Comment by TheOnionco** [comment]
figured it out on my ledger devices... thanks
